### ISSUE TITLE
About data file

### ISSUE THREAD

**Issue by AgentDS** [desternylin/perfed#1]
Dear authors, 

Thank you for your open-source code. It seems I cannot find the code to generate data partition for CIFAR10, FanshionMNIST, and EMNIST (only code for mnist and synthetic datasets are provided). I wonder whether you can upload the complete data partition code for the paper.

Best.

**Comment by desternylin** [comment]
@AgentDS Thanks for your attention. The data generation codes for CIFAR10, FashionMNIST and EMNIST have been uploaded to the '/data/' folder now.

**Comment by AgentDS** [comment]
Thank you very much!
